name: bitcoins
description: Bitcoin isolated witness dart implementation only supports isolated witness
version: 1.0.5
homepage: https://github.com/litaoh/bitcoin

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  pointycastle: ^1.0.2
  bs58: ^1.0.1
  hash: ^1.0.2

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
